name = "MyExample"
uuid = "3bad98ab-a195-48f5-b199-16e759e298f9"
authors = ["lianghao101"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
